name: rosetta_generator
description: >-
  Generator tool used with Rosetta annotations.
  This generates the helper and delegate classes
  for Flutter localizations.
version: 0.1.2
authors:
- Adam Hosszu <edemlonger@gmail.com>
- Renato Kiss <renato.kiss.dev@gmail.com>
- Tamas Agocs <agta91@gmail.com>
homepage: https://github.com/TeamWanari/rosetta

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  build: '>=0.12.6 <1.2.0'
  source_gen: ^0.9.1
  code_builder: ^3.1.3
  dart_style: '>= 1.0.0 <1.3.0'
  analyzer: '>= 0.32.4 <0.35.0'
  recase: ^2.0.0+1
  path: ^1.6.2
  glob: ^1.1.0
  rosetta: ^0.1.2

dev_dependencies:
  build_runner: ^1.1.0
  