name: rosetta_generator
description: >-
  Generator tool used with Rosetta annotations.
  This generates the helper and delegate classes
  for Flutter localizations.
version: 0.3.0
homepage: https://github.com/TeamWanari/rosetta

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: ">=2.0.0"
  source_gen: ">=1.0.0"
  code_builder: ">=4.0.0"
  dart_style: ">=2.0.0"
  analyzer: ">=2.0.0"
  recase: ">2.0.0 <3.1.0"
  path: ">=1.6.0"
  glob: ">=2.0.0"
  rosetta:
    path: ../rosetta/

dev_dependencies:
  build_runner: ">=2.0.0"
